# Generated by Django 6.0.1 on 2026-05-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.TextField(max_length=255, verbose_name='Место проведения события'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
